Code, Language and the Abyss: A History of Human⇄Computer Programming

* 001 The first program

** Jaquard loom

http://www.arthurchandler.com/napoleonic-expositions
The year is 1801 and the 2nd Exposition des produits de l'industrie française (the parochial aim of showcasing national genius, enterprise) is taking place in Paris in the courtyard of the Louvre. (Context: What else happened that year? Industrial revolution? Darwin? Dickens? Thomas Jefferson sworn in as 3rd President of US, Britain and France continue the French Revolutionary Wars, a prelude to the Napoleonic wars, Napoleon is not yet crowned emporer) Gold medals were awarded to displays of fine, elaborately-engineered clocks, furniture, pottery. September 24: Joseph Marie Jacquard, a sometime weaver and straw hat maker from Lyon only won a bronze. It was noted the loom replaces a weaving worker, leading to threats against his life.

Within 5 years, the government had recognised the importance of the loom, the advantage in weaving technology and the amount and quality and intricacy of the weaving it afforded, that they took posession of the patent, awarding Jaquard a pension for life, and within 10 years there were 11000 looms in France.

It took Jacquard several more years to perfect the device and make it commercially successful.

From: http://theinstitute.ieee.org/tech-history/technology-history/the-jacquard-loom-a-driver-of-the-industrial-revolution
How it worked: Jacquard did not invent a whole new loom but a head that attaches to the loom and allows the weaving machine to create intricate patterns. Thus, any loom that uses the attachment is called a Jacquard loom.

The state-of the art loom at that time was one in which the harnesses holding the threads were raised or lowered by foot pedals on a treadle, leaving the weaver free to operate the machine with his hands. The Jacquard loom, in contrast, was controlled by a chain of punch cards laced together in a sequence. Multiple rows of holes were punched on each card, with one complete card corresponding to one row of the design. Chains of cards allowed sequences of any length to be constructed, not limited by the cards’ size.

Each hole position in the card corresponded to a hook, which could either be raised or lowered depending on whether the hole was punched. The hook raised or lowered the harness that carried and guided the thread. The sequence of raised and lowered threads created the pattern. A hook could be attached to a number of threads to create a continuous, intricate design.

** Lady Ada

* 002 The first machines

** Von Neumann

First Draft of a Report on the EDVAC
https://www.wiley.com/legacy/wileychi/wang_archi/supp/appendix_a.pdf

As well as identifying the major components (logical, arithmetical, memory, i/o, clock, etc), proposes use of vacuum tubes as gates/triggers and thus a binary system for representing digits. Also parallel processing for multiplication etc. two's complement: "the sign plays the role of the digit farthest left".

also introduced the notion of registers for the hardware/software interface, such as the output of the arithmetic unit.

for those following along at home, the bit about programming comes right at the end.

14.1 maybe first use of the word code? "It is therefore our immediate task to provide a list of the orders which control the device, i.e. to describe the code to be used in the device, and to define the mathematical and logical meaning and the operational significance of its code words." orders received come from memory: stored code.

four classes of orders: carry out one of the 10 specific operations (eg. +-/*sqrt etc, primitives?); transfer a number from one place to another (load/store); transfer connection with memory to another place (jump or shift PC); control I/O.

chapter 10: the code. mixes numbers and 'orders' together (delineated by the first bit: 0 = number, 1 = order)

instruction packing and decoding: the first mnemonics. immediate mode load of the next number (cf transient/permanent jump).

table at the end of end of section 15 contains the first nascent machine code mnemonics.
